#!/usr/bin/env bash

buildImage() {
    local registry=$1
    local imageName=$2
    local version=$3
    local options=$4
    docker build ${options} -t ${registry}/${imageName}:${version} docker/${imageName} || { >&2 echo "Failed to build image ${imageName}"; return 1; }
}

build() {
    [[ $# -ge 2 ]] || { >&2 echo "Usage: $0 REGISTRY VERSION "; return 1; }
    local registry=$1
    local version=$2
    [[ "$3" == "localConfig" ]] || local pull="--pull"

    cp target/jwt-grant-performance.jar docker/jwt-grant-performance/jar/  || return 1
    buildImage ${registry} jwt-grant-performance  ${version}  "${pull}" || return 1
    }

build "${@}" || exit 1
