#!/usr/bin/env bash

version=DEV-SNAPSHOT
registry=local
stackName=jwt-grant-performance
localConfig=$1

mvn package -DskipTests || exit 1
docker/build-images ${registry} ${version}  ${localConfig} || exit 1
rm -rf docker/jwt-grant-performance/jar/*|| exit 1
VERSION=${version} REGISTRY=${registry} docker stack deploy -c docker/stack.yml --resolve-image=never ${stackName} || exit 1


