#!/usr/bin/env bash

run() {
    deployStackName=idporten
    deployHostName=localhost
    adminPort=$(getPort ${deployStackName} 'idporten-admin')
    idpPort=$(getPort ${deployStackName} 'idporten-openam')
    seleniumPort=$(getPort ${deployStackName} 'selenium')
    dbPort=$(getPort ${deployStackName} 'db')

    mvn verify -pl system-tests -PsystemTests -B\
    -DadminDirectBaseURL=http://${deployHostName}:${adminPort}/idporten-admin/\
    -DminIDOnTheFlyUrl=http://${deployHostName}:${idpPort}/minid_filegateway/\
    -DseleniumUrl=http://${deployHostName}:${seleniumPort}/wd/hub\
    -DdatabaseUrl=${deployHostName}:${dbPort}
}

getPort() {
    [[ $# -eq 2 ]] || { >&2 echo "Usage: $0 $FUNCNAME STACK SERVICE "; return 13; }
    stackName=$1
    service=$2
    docker service inspect --format='{{with index .Endpoint.Ports 0}}{{.PublishedPort}}{{end}}' ${stackName}_${service} || return 14
}

run ${@}